apiVersion: v1
kind: Secret
metadata:
    name: velero-s3-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:GvBO7eK6muqj0GnTs7huCFixnLF+hDZyNXAZvbvvonqtVLUvIgfytyWMPCwDJLL9Rqi5xCJ7ZPeu0V9wlMiiAAvPfDHuMn30Dk2NHQierzWqMbbTmgYZJWxTiDK6kFQwm+fxOW8hwhSLe+2BUeQ6wA==,iv:pEIk8Khdb1JqeQhxHj/K39d27XL9Kfo37yPsLWyVt40=,tag:3UnuyJgQR+IUoe9mH8m1NA==,type:str]
    values.yaml: ENC[AES256_GCM,data:OWZHaYEIpMdVPxfEyk9ElZfMVQaFOUVhPO9ryVS1rkvQpE6RisW1vJjtGoyIYD7KXxel4ojuCDqzcUbFpmY5HO4wg/it/ELeMAbcMBVOybNUUR1qthCHQC2WjwuGAyCSVCn2dKQBo7I6fMiYDpDweQizU3Gcuwp/VhiXUBpcvaYE+T4EF0g3g0fcvETR47gXLx0C9PlcWLp/NQi4H7WRf4bq2JF1IED/5yUW3Khv/YydmK+v02IUdaP9mPoLjOzKqicaQ9MNOEUyLsp/ghnGxxWB9WzR5aLsoI3olP3/DdbczQ4MgH37X0vBnSRYlEk1jQ894fKa9WrS83vwzj4YEHLVWIo=,iv:g7t9Tc4wdeursDvg3FjJg5Re99OgZnMqnR2dj4zIhks=,tag:Zikbs+rwB5vEqoydjS28qA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVGNKdVp3L054Q1k4aGRm
            K28zbFc5SFg0NzhXTG9vV1g2ejVSY2JRZW1zCjBPdmhYT2VQRGRMQVM1aHRZNE1C
            ZWttN0IybjAyN0diZUF5eW9qZ3U3K2sKLS0tIFV6b2V5YkhyYWpXZmpJbjlJK0Z5
            UHR5cWl3SEU2Ykg5V3haSXdvSDV4b1UKDf96FMZQaarZIYNGjYBgv5H4gA+qhzWs
            T6eRH82kWIUOsf4q0XaEY9LKlv1qnKiCtv6D6XHK2tBmZ9ZPzVPsOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7hkvapuyeup44gajxhc85vd0q4att0cd2t5ygpkffemhcchpqrslvqpdu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T10:07:04Z"
    mac: ENC[AES256_GCM,data:KCO8X0AiVPev/FVPrIo1IoP+dOtmO5WTj1DmVRfi41ZJMbnIogYhQ11tNBCxlMsdr+7jW7+FCoxeva/jYPYzq4FRH+91PykFE2ryEUEcn4j+GX1cDRCn+zDx/PSawFwTIGsSn1bjGVX+MDx0DsZm1CDcA/6XUdAKnlueNG5stss=,iv:sj60iYnTS/jIeGNh7wfCel9c9QVFwkxmxuNQRW9hxb4=,tag:FSVA92RtFFBVsmeomX1tIg==,type:str]
    version: 3.13.3
