apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
# cert-manager 
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  url: https://charts.jetstack.io
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "1.21"
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    crds:
      enabled: true
---
# Cloudflare's Origin CA issuer controller
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: origin-ca-issuer
  namespace: cert-manager
spec:
  url: oci://ghcr.io/cloudflare/origin-ca-issuer-charts/origin-ca-issuer
  ref:
    tag: "0.6.10"
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: origin-ca-issuer
  namespace: cert-manager
spec:
  interval: 30m
  dependsOn:
    - name: cert-manager
  chartRef:
    kind: OCIRepository
    name: origin-ca-issuer
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace