repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: bedag
    url: https://bedag.github.io/helm-charts
  - name: oauth2-proxy
    url: https://oauth2-proxy.github.io/manifests
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns

releases:
  # 1. Traefik

  # --- Taefik Namespace and tls-secret ---
  - name: traefik-tls-secret
    namespace: traefik-system
    createNamespace: true
    chart: bedag/raw
    version: 2.0.2
    values:
      - releases/traefik/secrets.yaml.gotmpl

  #--- Traefik Helm chart ---
  - name: traefik
    namespace: traefik-system
    chart: traefik/traefik
    version: 41.2.0
    disableValidationOnInstall: true
    needs:
      - traefik-system/traefik-tls-secret
    values:
      - releases/traefik/values.yaml

  # 2. OAuth2 Proxy

  # --- OAuth2 Proxy Secrets ---
  - name: oauth2-resources
    namespace: oauth2-proxy
    createNamespace: true
    chart: bedag/raw
    version: v2.0.2
    disableValidation: true
    values:
      - releases/oauth2/resources.yaml.gotmpl

  # --- OAuth2 Proxy Application ---
  - name: oauth2-proxy
    namespace: oauth2-proxy
    createNamespace: true
    chart: oauth2-proxy/oauth2-proxy
    version: "8.3.0"
    needs:
      - oauth2-proxy/oauth2-resources
      - traefik-system/traefik
    values:
      - releases/oauth2/values.yaml.gotmpl

  # 3. Velero Backup

  # --- Velero Secrets ---
  - name: velero-secrets
    namespace: velero
    createNamespace: true
    chart: bedag/raw
    version: v2.0.2
    disableValidation: true
    values:
      - releases/velero/resources.yaml.gotmpl

  - name: velero
    namespace: velero
    createNamespace: true
    disableValidationOnInstall: true
    chart: vmware-tanzu/velero
    version: " 12.2.0"
    values:
      - releases/velero/values.yaml.gotmpl

  - name: velero-schedule
    namespace: velero
    createNamespace: true
    chart: bedag/raw
    version: v2.0.2
    disableValidation: true
    values:
      - releases/velero/schedule.yaml.gotmpl

# 4. ExternalDNS 

  # --- ExternalDNS Secrets ---
  - name: externaldns-secrets
    namespace: external-dns
    createNamespace: true
    chart: bedag/raw
    version: v2.0.2
    disableValidation: true
    values:
      - releases/externaldns/resources.yaml.gotmpl

  - name: externaldns
    namespace: external-dns
    createNamespace: true
    chart: external-dns/external-dns 
    version: " 1.22.0"
    values:
      - releases/externaldns/values.yaml.gotmpl