apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 03-platform
  - 04-deploy
secretGenerator:
  - name: shared-env
    namespace: flux-system
    envs: [.sops.env]
generatorOptions:
  disableNameSuffixHash: true