apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 30m
  dependsOn:
    - name: paperless-redis
    - name: traefik
      namespace: traefik-system
    - name: oauth2-proxy
      namespace: oauth2-proxy
  chartRef:
    kind: HelmChart
    name: base-app
    namespace: flux-system
  values:
    appName: paperless
    dnsTarget: "${SERVICE_DNS_NAME}.${DNS_ZONE_NAME}"
    ingressHost: "docs.${DNS_ZONE_NAME}"
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 3.0.5
    service:
      port: 8000
    ingress:
      - path: /api
        extraMatch: "HeaderRegexp(`User-Agent`, `QuickScan`)"
        middlewares:
          - name: strip-auth-headers
            namespace: oauth2-proxy
      - path: /ws
        middlewares:
          - name: strip-auth-headers
            namespace: oauth2-proxy
      - path: /
        middlewares:
          - name: strip-auth-headers
            namespace: oauth2-proxy
          - name: errors
            namespace: oauth2-proxy
          - name: auth
            namespace: oauth2-proxy
    env:
      PAPERLESS_SECRET_KEY:
        valueFrom:
          secretKeyRef: { name: paperless-secrets, key: PAPERLESS_SECRET_KEY }
      PAPERLESS_ADMIN_USER:
        valueFrom:
          secretKeyRef: { name: paperless-secrets, key: PAPERLESS_ADMIN_USER }
      PAPERLESS_ADMIN_PASSWORD:
        valueFrom:
          secretKeyRef: { name: paperless-secrets, key: PAPERLESS_ADMIN_PASSWORD }
      PAPERLESS_REDIS: "redis://paperless-redis-svc:6379"
      PAPERLESS_FORCE_SCRIPT_NAME: "/docs"
      PAPERLESS_URL: "https://docs.${DNS_ZONE_NAME}"
      PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://docs.${DNS_ZONE_NAME}"
      PAPERLESS_CORS_ALLOWED_HOSTS: "https://docs.${DNS_ZONE_NAME}"
      PAPERLESS_LOGOUT_REDIRECT_URL: "https://auth.${DNS_ZONE_NAME}/oauth2/sign_out"
      PAPERLESS_PORT: "8000"
      PAPERLESS_USE_X_FORWARD_HOST: "true"
      PAPERLESS_ENABLE_COMPRESSION: "false"
      PAPERLESS_CONVERT_MEMORY_LIMIT: "32"
      PAPERLESS_CONSUMER_DISABLE: "true"
      PAPERLESS_TIME_ZONE: "Europe/Luxembourg"
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
      PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: "HTTP_X_AUTH_REQUEST_USER"
      PAPERLESS_DISABLE_REGULAR_LOGIN: "true"
      PAPERLESS_OCR_LANGUAGES: "rus eng fra"
      PAPERLESS_OCR_LANGUAGE: "rus"
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "1"
    storage:
      data:
        mountPath: /usr/src/paperless/data
        accessMode: ReadWriteOnce
        size: 500Mi
      media:
        mountPath: /usr/src/paperless/media
        accessMode: ReadWriteOnce
        size: 2Gi