appName: paperless-redis

image:
  repository: docker.io/library/redis
  tag: 8.10.1

service:
  port: 6379

resources:
  requests:
    memory: "32Mi"
    cpu: "50m"
  limits:
    memory: "64Mi"
    cpu: "100m"

storage:
  data:
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 500Mi
    noBackup: true