apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:C2H0Jr/qd+5u1A6TacMYPX22fiUYfwlazF4G8FhLKgbxh34G7NPAvhqifpqA9A==,iv:porJ+fMfOKK+CknJA6zrmESpHTiDw1GBJUM+vcvdN74=,tag:At/AdQ/31aLi7bNyHfAsZg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:pvpVU2f6xiucr08gBg==,iv:TYCmGzvT47uT1mxxjcEEaP/CimBRNNhdQYrLxQOt+IY=,tag:qnfzL0nKu5MBW3o2UbEeXQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:BqUCeR7aiRtN9ZqMrrU48g==,iv:3/VQcZpUGLPP9FDRFyBnLZBVN4cQlkqCkxufXREpqxA=,tag:MhWchFk5W+FAclBBGn3qVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMnNPdmN3dnRhL3o4TFJW
            c3htYlg2U3pOdXlwcE85WlBzS0p6bml6TUVFCmRpK0hjMk9wL2RSV0pnRk9vRFAz
            OVIyaTJ4c3ErQmdOelVNMWZFOXN4T3cKLS0tIFYwdTJIM0lDUTdDQmJVR3ZpUlJY
            R0lhcUxnUjhtL2dkTGxoRjBXUUl0ZTAK3A1pf6/hWa2OEZm9xB0HWSuqAXk83avZ
            Mp7BTF81dqhxM+MlsW0tf9jhm5KTDGlwLZac4bswGu017uXXcZAy3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7hkvapuyeup44gajxhc85vd0q4att0cd2t5ygpkffemhcchpqrslvqpdu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:40:05Z"
    mac: ENC[AES256_GCM,data:MFq/wKYaC9Vas7Un1b/4qUXOxu8DLhTpmwuv2uBT5lTPFncO72UzWNhNKnz/06Rajdr/if1aHL+LlWNu7NUvJIkarWCdXIIlAwKucsekP1LH0cvU+kk2H0HRM73ZqekBy3JBz+tZn/fnZd/pgBBBf9e5CTx2P8FQRG73OIZmA5U=,iv:5ghwU3tK64metAeyTRODiTo20A0+rZY8bAYOP5mXgKA=,tag:OE+9o2dE3Ny2t3WESMWDRw==,type:str]
    version: 3.13.3
