appName: taskframe-frontend

image:
  repository: ghcr.io/alex-sviridov/taskframe
  tag: 19a4457

service:
  port: 8080

ingress:
  - path: /task
    stripPrefix: true

env:
  - name: PB_UPSTREAM
    value: "taskframe-backend-svc:8090"

  - name: BASE_HREF
    value: "/task/"
  
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"
