apiVersion: v1
kind: Secret
metadata:
    name: papra-secrets
    namespace: papra
stringData:
    auth-secret: ENC[AES256_GCM,data:Z+LpGoiQQKN4y04H/P0ARRJH7u1CloF8lBOLTUX8iccYE5cZnGgA+2mhmVZv2Q==,iv:tIa3q4nQ1jsUzh5FW2pe7zaKAhW5o3wR7W/x1YXpUj0=,tag:JG9M3uTeHAPE5iPJr2EguQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQU5MdTRTRVNhSCtrRVdH
            TzB6K3ZJWkMzVW1kZ0h1UFNKUFpHbVYxSmk0Cjc5NllpUWdlQmc2S3pxSlFIbzho
            MnpNdUlldmJhWGMxODg4dEVpNDhaZzAKLS0tIDZkVXNpWG4vbDJ6REJFRUtZRnhy
            WDhKMkZoaTFFUm9BbjAwS3dFakZrNGcKtfVxdFL56rHes5WtwEBbGUyiWozqOLd8
            12s5dPpoF6DOmOSlKNfvlx0VJrEftvpl78lmmaQfsQPw5rn2sprY4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7hkvapuyeup44gajxhc85vd0q4att0cd2t5ygpkffemhcchpqrslvqpdu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:19:19Z"
    mac: ENC[AES256_GCM,data:BOIBlnH7cLOBFG/lqh59NnWStXOEcSsBKh79PsL1+6JHZldWkOcpt4MZrKdFuIFdflProlt0/tiBMr+Iof7Q/8Ngt1+hp5DMtoEskozzcbHdf0V6NZUAuyboIUHBIjyQ+6mCtuouyDsGLTdAKqbFE8Xin7REVcd/0hLSEuih3Sw=,iv:VUZ2hV0Yj6ABuRScoMjZnnFnkhMPaLNySChpSqEEVrU=,tag:akngkD9+mL6TZHdUzVWl+Q==,type:str]
    version: 3.13.3
