apiVersion: v1
kind: Secret
metadata:
    name: papra-secrets
    namespace: papra
stringData:
    auth-secret: ENC[AES256_GCM,data:3eIv7w5ARsQmdLswEuMD6iTfiIf1zAMpG4H6n8meTryhwhFmUvkt+9b/dFY2NQ==,iv:xXNN7MQaCIyFWt0XddIYdLD2grQO88bUqJ35vO7/lj4=,tag:HiyW8LjCCtLrBLtm/xiEvA==,type:str]
    github-client-id: ENC[AES256_GCM,data:Sam8U9SPFQ94b5s0athqGu6jbtM=,iv:h/BxJVDUOsD9bte/3X9cKRgO1uwsy0bWhoYAwS5NIew=,tag:v76l2lOW4Zp1pw3IQKZ2pQ==,type:str]
    github-client-secret: ENC[AES256_GCM,data:aBI91h/d+ZYoiCxiZ9c1HFbGHV16Qm7Cy0baxefg3QDXdilzdpFh7A==,iv:uMRJH4zJPDwb1ZE4g0GwFTmqzPUkkHO6NScjq3rMB1s=,tag:C+uezMdxUN7orBvOt+q9pA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOG5JZnBjallwZi95Ly9i
            YjRrZ0pMK082bVZNTGlVb1JhSngvTWh4d1EwCnhReGNVNWVVeUQ4REZZeDFXMGMv
            Y2MreXVnRWpMV2Znb0p5OTY0NEZmTlUKLS0tIGRjamxjSWNPT3hQbjcvbDY4QThn
            YTRoRjJrVElqRGMzVklxUWI2UnRlbXcKOmbpqNcApNJJRqdG+6JFmq2p6gtEolpA
            zfrMZPUW5B39d4CQRClT77qI8jKX6k1s9HkRqpicrgrPUPOxZVH2QQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7hkvapuyeup44gajxhc85vd0q4att0cd2t5ygpkffemhcchpqrslvqpdu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T17:25:34Z"
    mac: ENC[AES256_GCM,data:OuUjSFZkEPyIV3epkhLcxLC3iHZTIDrniKDrwVwX3bJ+Duehi29SC/x2bSW/YR8mXLO0dPUWDNOBRdi1WQCutmUZCbqqou4Rc9SlkAm3HQvNmcaTh8ApvmaKYG8LHkI5btaI2YwnPe7BlRYiWpEo8mLhXouBw/m31+4Nt57To9U=,iv:OzMBQxRdsptkTnvVfzX744h02D7K4hNSYWrawsWdkdg=,tag:qD+kiSNdOPUNOQb/VcJvfg==,type:str]
    version: 3.13.3
