apiVersion: v1
kind: Secret
metadata:
    name: traefik-secrets
    namespace: traefik-system
stringData:
    ORIGIN_CA_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:TAnxkzu9V9AOlvX8oihcWmWGo08Am0zcF6sBXOTh7QtvNE9dzzeXt/3tshQ1EVBBxfLQF+M=,iv:Tje581Sfo7wUBBDIyQ1pxYylxxCaRlftlqcZNukfiNY=,tag:DG6MlEx68stwRBnLQ2w/Mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdDIrL3JRS29BSjQrSmNq
            OE1DRUp3WUI3OG50Q1JhK3djaUNYN0dVL2hNCi9Ia040K2h6OVhBVlVLMXpBTElq
            cEw0dFkxK2I1YTRkZW5kR3pLdjZWUW8KLS0tIEgzY1ZDSHFHemgydXhFRWJZVXYy
            bWlpSU9DeUgyeUIveTl0aE5rOWx0KzQKQf2t15yaS322U2R4t0VAwGkP5LBK7qfQ
            ezlbCMCBijeXgQwXoxdQqjO9maqJgeKyqNXvMmM+viQ3Yzqpg9gFvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7hkvapuyeup44gajxhc85vd0q4att0cd2t5ygpkffemhcchpqrslvqpdu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T09:52:07Z"
    mac: ENC[AES256_GCM,data:QRsh5Kek0tIbrmKo/yT+Vbv/L5bcF66dlBsQnjGpJZpSsBqZAGs368/WpyXAqRPg819YAw2m9Tz7MkdExqVDZnzHrrrHtJwnFgxi+IyiOeF/osFdON6y5GW0G5FLHxej7G9fnIKEVfPF2bmrE5QXXs+hvQ3g2KFWJHIL99czAC0=,iv:MUCVqZlkJNj8sDT2gqpeh57ZVl1cshszaxOYMlnjyjY=,tag:Irl3ObTxfHVPjTr2nHowVA==,type:str]
    version: 3.13.3
