apiVersion: v1
kind: Secret
metadata:
    name: traefik-secrets
    namespace: traefik-system
stringData:
    cloudflare_token: ENC[AES256_GCM,data:7NrK1fiL1R6TBCjODDoVlvERl3iizWeckkWG0g+lZBcYSuGqXf/4INNdCGLHOg9KE5A/9yk=,iv:0pzriIPFEqRR54UgOEix1kVjIinDyvv22HIXLxliy6k=,tag:YB1o9KZse+C83MFOQ0UwHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTFFBaStpQnJFWXMzaitp
            Y054YUZReXhZalRtTnFGbWFlQnY0WnR6ZUJRCkM2NHJYTlZXQlRPa2dlSGdIQzRH
            eWlBbXUrME9WK3gvUUxxdnVUVjZQUHcKLS0tIFRjOUl5c0praFdKM1UvZkdOWkE0
            b2lGYUszeHhuQXBGY3pRNjFLd3I1eGsKWgDN7ePGfrW/aGWoiF1kJNg47Wi53MJ1
            KcHcWblVyKYmC1oLwX0S9hmVzEIyrmbDhzyPrzg2LZ8GmyX9CGnCkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7hkvapuyeup44gajxhc85vd0q4att0cd2t5ygpkffemhcchpqrslvqpdu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T10:01:24Z"
    mac: ENC[AES256_GCM,data:PECkknbuc9VjBBu8wVdizdw85YOX3z3iEmSOAPG4JuOwlZiE3JCCcKwmijgGVWLl6TD5yc6+RIyfYjbWTOoDVKMQl2vA71t75tMCpIzwo3bwRLseyEFS51M5Ixt7RXzqj/ppXix8SALJnyAQXSkljQpiEeAMpQjEFNoaZEQfsoc=,iv:5gT+uWPWeUE/akUUMJlkfuGRZHtUij8bdFscre9pmn0=,tag:e4lWS1qxCBtpHYMa7P2ZOg==,type:str]
    version: 3.13.3
