apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lexi-backend
  namespace: lexi
spec:
  interval: 30m
  chartRef:
    kind: HelmChart
    name: base-app
    namespace: flux-system
  values:
    appName: lexi-backend

    image:
      repository: sviridov12/lexi
      tag: backend-sha-3ed6c4d1784302b85d56be044b6a2e644848e508

    service:
      port: 8090

    ingressHost: "lexi.${DNS_ZONE_NAME}"
    ingress:
    - path: /api/
      stripPrefix: false

    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "1"

    storage:
      data:
        mountPath: /app/pb_data
        accessMode: ReadWriteOnce
        size: 2Gi

    env:
      CLAUDE_API_KEY:
        valueFrom:
          secretKeyRef: { name: lexi-secrets, key: claude-api-key }

      PIXABAY_API_KEY:
        valueFrom:
          secretKeyRef: { name: lexi-secrets, key: pixabay-api-key }
