apiVersion: v1
kind: Secret
metadata:
    name: lexi-secrets
    namespace: lexi
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    claude-api-key: ENC[AES256_GCM,data:vFgRboz5feRVB1JGoeEOpCV/4MnK6eKjTR/tvlAUBlNLqDYi1KFb6e3QkYyaGYUYsi/BjciThotCVBBwc9TMFlUDkVZ0Eyp/sIagz3ubqc6LxEdQ5oMJGvwYiju7LMFxrU3NrdtW2h+PcHIL,iv:iUIICD3zOhPUCStd8bjsU6IZgd7XUmryEGrh5Z5mrL8=,tag:nkIveAjHQls3bX9x4LkyoA==,type:str]
    pixabay-api-key: ENC[AES256_GCM,data:dEt81DHrsNqRivHWYCoJn4FrT+IzzPf25q9XW/6+O4raTQ==,iv:M4nxO/UJO2+o7AH/eZE9PP+i1nENVRRCPcLGOB+6r+A=,tag:c2FzVs7d+R1lujQ2MBiVvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNHFENXM0bnFtaW5oNDVr
            ODl2enNYVCtJOUs2UmtiWlZBc3FDZzJxV21VCndYNXZjY0pySDRUSVdhOHpXTmxs
            Vm01cjVBRGc2SWRvU3g3Q2Z2SDRBbTgKLS0tIDd4K0xBM2diZGs1QldPK1MxSDNn
            TWFqK3lnZDc2YW1URHNsNHJ1Yldnbm8Kskc0NDgUfhJ9Z9LxTAUbIToqonj+nxci
            5f7pGoPbZrA0v+Z13U4ZWbZtdjBxX9abwJSyrru6BR/f0v64iYAhow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7hkvapuyeup44gajxhc85vd0q4att0cd2t5ygpkffemhcchpqrslvqpdu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T17:57:05Z"
    mac: ENC[AES256_GCM,data:diNwG2XLM28DMV29hQc3WfappNS4zHg581G2UQ0qRQBkdLyL829a3mnYW2EfccIVXc6Q7oUnBeZWF7pxJmCaNYD3crcx9mhWHywPG8qG2Vgnr7uwg8XwV+fod0gi0zF5UZjKYfmzqcWxYmjI36D1RA0UfTYVa4RWEof9Yboxr3M=,iv:prql8POGqtUuX34NpMXfovXDatR6mbSztwgCTjjDr1E=,tag:NmGlyEPMqrjazN4glop/Bw==,type:str]
    version: 3.13.3
