apiVersion: v1
kind: Secret
metadata:
    name: lexi-secrets
    namespace: lexi
stringData:
    claude-api-key: ENC[AES256_GCM,data:SMLcnAZHSE54hZF+1V1rZjSruMMFunBh8G3u/aQOPww+a9qmRWqEWF3l2fA3XO2EvjVa+BvOt1eyCsVeM8L9e73gBStGUg0BAwCSrQiclSl+dccl1HvpmCpN3vx3PaOHb+ErSSvBRHclui5p,iv:VByvf2c2Oji2B30qwR7mWcXzdUrsaA0zHumZc+/tab8=,tag:VcVBylIgt1nukHjGGZ13Eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcnl2ZG9tc0Fvak1IdUxx
            dUVKc0kwalJFRXI3bnNaVDNIMGZTRGN5SXo4CndXK2ZGVDFFamlPSXJWOStEWXNL
            a24yZUc2RnQvOHc0ZkozZ3VQZHI4ZzQKLS0tIFVRNHNURGdVSkVoWUo3MUNoc0lJ
            N1FldjBKVnVSbHlpU0tPOFRoWTkzS0UKMNIMDaDQtVQHpQkKMrJmBBnBLWVurgEB
            2tEKpEV6R8byi1ecGtAAxL3PfX5grZe1KhfMgCEenb+EtwqlMGjuzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7hkvapuyeup44gajxhc85vd0q4att0cd2t5ygpkffemhcchpqrslvqpdu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:53:00Z"
    mac: ENC[AES256_GCM,data:uszOUWl/gTjvYGlI0SXGiVS5fx0zqDRWLoevp+IZZe8V3//b24eth2ZoHj3MRZ6STRaG31arzf9nmgggxecxzQD/DdPxIaoZm9/P96rkmv/46WasrmF/y1MDBFLdhG74anetOBnQ65GPpaESZq5fcx6PwsENNOOSMhHUYbmAQXE=,iv:4YgHAhLOVcN/Qvs9PlrHzeuI2obp2We/1+sBL3DGqO8=,tag:tk+2yARqf4pZANoLL1UJOg==,type:str]
    version: 3.13.3
