apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lexi-vocabulary
  namespace: lexi
spec:
  interval: 30m
  chartRef:
    kind: HelmChart
    name: base-app
    namespace: flux-system
  values:
    appName: lexi-vocabulary

    image:
      repository: sviridov12/lexi
      tag: vocabulary-sha-3ed6c4d1784302b85d56be044b6a2e644848e508

    service:
      port: 8080

    ingressHost: "lexi.${DNS_ZONE_NAME}"

    ingress:
      - path: /

    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "500m"
