{{- if .Values.ingress }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}-route
spec:
  entryPoints:
    - websecure
  routes:
    {{- range $route := .Values.ingress }}
    - match: Host(`{{ $route.host | default $.Values.ingressHost }}`) && PathPrefix(`{{ $route.path }}`)
      kind: Rule

      {{- if or $route.middlewares $route.stripPrefix }}
      middlewares:
        {{- if $route.stripPrefix }}
        - name: {{ $.Values.appName }}-{{ .path | replace "/" "-" | trimAll "-" }}-stripprefix
          namespace: {{ $.Release.Namespace }}
        {{- end }}

        {{- range $route.middlewares }}
        - name: {{ .name }}
          namespace: {{ .namespace | default $.Release.Namespace }}
        {{- end }}
      {{- end }}

      services:
        - name: {{ $.Values.appName }}-svc
          port: {{ $.Values.service.port }}
    {{- end }}
{{- end }}