apiVersion: v1
stringData:
    client-id: ENC[AES256_GCM,data:CoPbi1632FtTFaymocZguY65aB0=,iv:LDz76cWS6g3bmQhUxbtS4IzzxLjLeG4UMpxhqyJYs2k=,tag:OHTIJghSrIPcSsbbOAPS3A==,type:str]
    client-secret: ENC[AES256_GCM,data:K/A7yW5+VdFDz8qN4+v3a5FKu3j01L1271o9TAtidu/0MNb90dmoug==,iv:dEI1aoBnCYsgU6OOt3z1NC6YzYHSFAwYiC2ZzO/QJTk=,tag:jSf3CY3kaxqaE3ppnYCy6A==,type:str]
    cookie-secret: ENC[AES256_GCM,data:XyUWBD3YotD7vUpA7xPYni5ePlc7p+uuy9Lr4rRUGRXHRpkphEkYtryhYA==,iv:QzAj5EZ0BK0XR0CP6KTvpkxaFUuw71d+3spL0X+m4X4=,tag:eX2pc97Hd12XwOQnieJo+w==,type:str]
    github-users: ENC[AES256_GCM,data:tFf9P02xz4yXp+pKtw==,iv:vPBqQUE6mNpt7U/pvvpSxCeaObPCuD0ti6jVhNWQGso=,tag:1nm4y2wwRfziG4Iqt6lGRA==,type:str]
kind: Secret
metadata:
    name: oauth2-secret
    namespace: oauth2-proxy
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWGFBSWVBb1ZGZTJNNTRw
            SEwrMCtleUcyaWlMbnhjbHB2akg2cnRjUkJJCnFWT0hIcmlXSVBJTjc4cG1TQkJF
            dWJVSlA5OEJTUXZGT1lXUndJREwzYVUKLS0tIEtCbWZUMG5qUEVvLytseUNFczJX
            ditNY1FuYjBJM21ldmRnNmV4S245TkkKTjcvXhtM/TZ74yzH9JptkGfVd9XGYrYs
            M+edoETTNIY3O6IGHUztj1yEc1sYmtBhI0nAPCA8wlx5eXUJc+Ezyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7hkvapuyeup44gajxhc85vd0q4att0cd2t5ygpkffemhcchpqrslvqpdu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T15:32:30Z"
    mac: ENC[AES256_GCM,data:NOsg5baUbSds3GHWRATSu1EgUUWJS7oeJm0+8Pw26y6W3GQH2JNiHYMFec2fX+H51093e7tT1nkJmL/5PyxJPRAj5CXCs/s+b/L22Bqo4DXCMaDS5HqLvWIQuLrqAFy0C1ZskaJ9J1Z3SJzCvV8pEwlpGPaHo/J5j15scurefg0=,iv:f+bVFNR/VIpnpw6tscN/RbXmaCJ26MVk1aZlRi1lcE0=,tag:GHmi9e8p54JPNtKHG/l3KQ==,type:str]
    version: 3.13.3
