appName: readtrail-backend

image:
  repository: ghcr.io/alex-sviridov/readtrail/backend
  tag:  sha-1aaa453 

service:
  port: 8090

ingressHost: readtrail.net
ingress:
 - path: /api/
   stripPrefix: false

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

storage:
  data:
    mountPath: /pb/pb_data
    accessMode: ReadWriteOnce
    size: 1Gi
