appName: readtrail-frontend

image:
  repository: ghcr.io/alex-sviridov/readtrail/frontend
  tag: sha-1aaa453

service:
  port: 8080

ingressHost: readtrail.net

ingress:
  - path: /

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"
