apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - charts/base-app.yaml
  - releases/whoami.yaml
  - releases/audiobookshelf.yaml
  - releases/paperless
  - releases/taskframe