apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secrets
    namespace: external-dns
stringData:
    cloudflare_token: ENC[AES256_GCM,data:VghfvihCd4j/vim79/P1EVJPudlExIC4j/cLRYli1+yrj+uNbJxUKe3Fj/Zb8PO3tH8ylYQ=,iv:CHW04QoPeee0/AWhzySjIetv2uP2fPM+do8GVH/LHYk=,tag:09mqem2k2uiTfe+9PoAjXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cFQrbTg4WUg3UzdlYnRT
            UTM3cXNtMTNqbHRvaFZkZFhlN1FvQ2kvU0ZRCnk0cTBPekpBRzdmMC9jM2ludk83
            TkM0LzM1eG85T1kzK2JsOWhmOXpJS1UKLS0tIDNzN1ZDdlhiVnFOM2dPcTE0TDhw
            bUJHdWQ0QlYySnYzY0dEQk9oZE5EM3cKHaBGMyNFcO+jcZrptGl6m62tF1rFKVog
            RxU8M3Amz3tzIYr/PrHMQ8LmtDPcc0KeOx4nUkNBLoPoHMwT6QSC6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7hkvapuyeup44gajxhc85vd0q4att0cd2t5ygpkffemhcchpqrslvqpdu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T10:06:22Z"
    mac: ENC[AES256_GCM,data:AMQJZb5L1RAB3dfWLMgPHbp33opM7XQ4yxy/itbRZPuEG+nM1XNdExaaZHP/00IJ9uO9m3t2QM+UE4jlOmepIJTMuChhw8LVOKuFNkZKNkCFfnQRA1bs/XrF8eZpsZSND8IshBR2a7+sZe5zudFiZmf5Ma2jtVk6yh9QQXPL94g=,iv:9SfuEefd+a/2LdJn2/4nHI13fEEFQfWwZbeVS8uAcsE=,tag:WWMhYIxAwf7188yo6VGVww==,type:str]
    version: 3.13.3
